version: '3'

services:
    bot:
        build: .
        volumes:
            - ./:/bot
        command: python main.py
        working_dir: /bot
        restart: always
        stdin_open: true
        tty: true
        init: true
        environment:
          - BAIDU_API_KEY=
          - BAIDU_SECRET_KEY=
          - TELEGRAM_BOT_TOKEN=
          - TELEGRAM_API_ID=
          - TELEGRAM_API_HASH=
